export const SENSORS = [
  {
    key: "humidity",
    label: "Env Humidity",
    unit: "%",
    icon: "💧",
    min: 0, max: 100,
    thresholds: { low: 30, high: 80 },
    safe: [40, 70],
    color: "#38bdf8",
    baseVal: 58,
    drift: 3,
    description: "DHT11 — field1",
  },
  {
    key: "envTemp",
    label: "Env Temp",
    unit: "°C",
    icon: "🌡",
    min: 15, max: 50,
    thresholds: { low: 18, high: 40 },
    safe: [20, 35],
    color: "#34d399",
    baseVal: 30,
    drift: 1,
    description: "DHT11 — field2",
  },
  {
    key: "bodyTemp",
    label: "Body Temp",
    unit: "°C",
    icon: "🌡️",
    min: 25, max: 42,
    thresholds: { low: 36, high: 38 },
    safe: [36.1, 37.5],
    color: "#fb923c",
    baseVal: 30.69,
    drift: 0.5,
    description: "DS18B20 — field3",
  },
  {
    key: "moisture",
    label: "Moisture",
    unit: "%",
    icon: "🌊",
    min: 0, max: 100,
    thresholds: { low: 20, high: 85 },
    safe: [30, 75],
    color: "#67e8f9",
    baseVal: 50,
    drift: 3,
    description: "Analog sensor — field4",
    // Raw 0-1023, dry=high → convert to %
    transform: (raw) => Math.round(100 - (parseFloat(raw) / 1023) * 100),
  },
  {
    key: "ph",
    label: "pH Level",
    unit: "pH",
    icon: "⚗️",
    min: 0, max: 14,
    thresholds: { low: 6, high: 8.5 },
    safe: [6.5, 7.5],
    color: "#a78bfa",
    baseVal: 9.6,
    drift: 0.2,
    description: "pH sensor — field6",
  },
];

export const STATUS_COLORS = {
  good:     { bg: "#052e16", text: "#4ade80", border: "#16a34a" },
  warning:  { bg: "#2d1a00", text: "#fbbf24", border: "#d97706" },
  critical: { bg: "#2d0a0a", text: "#f87171", border: "#dc2626" },
};