export const SENSORS = [
  {
    key: "humidity",
    label: "Env Humidity",
    unit: "%",
    icon: "💧",
    min: 0, max: 100,
    thresholds: { low: 30, high: 80 },
    safe: [40, 70],
    color: "#38bdf8",
    baseVal: 58,
    drift: 3,
    description: "Environmental humidity",
  },
  {
    key: "envTemp",
    label: "Env Temp",
    unit: "°C",
    icon: "🌡",
    min: 15, max: 50,
    thresholds: { low: 18, high: 40 },
    safe: [20, 35],
    color: "#34d399",
    baseVal: 30,
    drift: 1,
    description: "Environment temperature",
  },
  {
    key: "bodyTemp",
    label: "Body Temp",
    unit: "°C",
    icon: "🌡️",
    min: 25, max: 47,
    thresholds: { low: 36.1, high: 38.5 },
    safe: [36.1, 38.5],
    color: "#fb923c",
    baseVal: 36.5,
    drift: 0.5,
    description: "Body temperature",
    transform: (raw) => parseFloat(raw) + 5,
  },
  {
    key: "moisture",
    label: "Moisture",
    unit: "%",
    icon: "🌊",
    min: 0, max: 100,
    thresholds: { low: 20, high: 85 },
    safe: [30, 75],
    color: "#67e8f9",
    baseVal: 50,
    drift: 3,
    description: "Wound moisture level",
    transform: (raw) => Math.round(100 - (parseFloat(raw) / 1023) * 100),
  },
  {
    key: "ph",
    label: "pH Level",
    unit: "pH",
    icon: "⚗️",
    min: 0, max: 14,
    thresholds: { low: 4.0, high: 5.5 },
    safe: [4.0, 5.5],
    color: "#a78bfa",
    baseVal: 4.8,
    drift: 0.2,
    description: "Wound pH level",
  },
];

export const STATUS_COLORS = {
  good:     { bg: "#052e16", text: "#4ade80", border: "#16a34a" },
  warning:  { bg: "#2d1a00", text: "#fbbf24", border: "#d97706" },
  critical: { bg: "#2d0a0a", text: "#f87171", border: "#dc2626" },
};